apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwfvn9464-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwfvn9464-tenant-component
    app.kubernetes.io/part-of: loadwfvn9464-tenant-app
  name: loadwfvn9464-tenant-component
  namespace: loadwfvn9464-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadwfvn9464-tenant-component
status:
  loadBalancer: {}
